# Generated by Django 4.1.3 on 2022-12-15 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categories',
            name='icon',
        ),
        migrations.AddField(
            model_name='categories',
            name='image',
            field=models.ImageField(default='', upload_to='home/images'),
        ),
    ]
