# Generated by Django 4.1.3 on 2022-12-20 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_video_time_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='field',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
