# Generated by Django 4.1.3 on 2022-12-20 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_language_course_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='DeadLine',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
