# Generated by Django 4.1.3 on 2022-12-20 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_usercourse'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='validity',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
