# Generated by Django 4.1.3 on 2022-12-29 04:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_remove_payment_payment_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='razorpay_payment_id',
            new_name='payment_id',
        ),
    ]
