# Generated by Django 4.1.3 on 2022-12-29 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_rename_razorpay_payment_id_payment_payment_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='signature_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
