# Generated by Django 4.1.3 on 2023-01-03 05:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_answer_paper_questions_test_delete_testseries_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.usercourse'),
        ),
    ]
