# Generated by Django 4.1.3 on 2023-01-07 07:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_ppr'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ppr',
            name='thumbnail',
        ),
        migrations.CreateModel(
            name='Que',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qs_no', models.IntegerField()),
                ('questions', models.TextField()),
                ('answers', models.CharField(max_length=20)),
                ('option_a', models.TextField()),
                ('option_b', models.TextField()),
                ('option_c', models.TextField()),
                ('option_d', models.TextField()),
                ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.course')),
                ('ppr', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.ppr')),
            ],
        ),
    ]
