# Generated by Django 4.1.3 on 2023-01-07 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0023_remove_ppr_thumbnail_que'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ppr',
            name='subject',
        ),
        migrations.AddField(
            model_name='que',
            name='subject',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
