# Generated by Django 4.1.3 on 2023-01-07 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0025_remove_ppr_preview_que_disc_que_time_duration_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='que',
            name='time_duration',
        ),
    ]
