# Generated by Django 4.1.3 on 2023-01-09 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0026_remove_que_time_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='ppr',
            name='slugn',
            field=models.SlugField(blank=True, default='', max_length=500, null=True),
        ),
    ]
