# Generated by Django 4.1.3 on 2023-01-14 06:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0030_ans'),
    ]

    operations = [
        migrations.AddField(
            model_name='ans',
            name='ppr',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.ppr'),
        ),
    ]
