# Generated by Django 4.1.3 on 2023-01-14 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0031_ans_ppr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ans',
            name='answer',
            field=models.CharField(default=0, max_length=20),
        ),
    ]
