# Generated by Django 4.1.3 on 2023-01-14 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0032_alter_ans_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='ans',
            name='score',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='ans',
            name='answer',
            field=models.CharField(max_length=20),
        ),
    ]
