# Generated by Django 4.1.3 on 2023-01-17 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0034_result'),
    ]

    operations = [
        migrations.AddField(
            model_name='ans',
            name='correct_answer',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='ans',
            name='que_no',
            field=models.IntegerField(default=1),
        ),
    ]
