# Generated by Django 4.1.3 on 2023-02-04 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0038_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='thumbnail',
            field=models.ImageField(null=True, upload_to='Media/subject'),
        ),
    ]
