# Generated by Django 4.1.3 on 2023-02-04 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0040_videolecture'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subject',
            old_name='name',
            new_name='subject_name',
        ),
    ]
