# Generated by Django 4.1.3 on 2023-02-04 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0042_rename_videolecture_video_lecture_e_book'),
    ]

    operations = [
        migrations.AlterField(
            model_name='e_book',
            name='book',
            field=models.FileField(null=True, upload_to='Media/book'),
        ),
    ]
