# Generated by Django 4.1.3 on 2023-02-04 10:17

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0043_alter_e_book_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='slug_s',
            field=autoslug.fields.AutoSlugField(default=None, editable=False, null=True, populate_from='subject_name', unique=True),
        ),
    ]
