# Generated by Django 4.1.3 on 2023-02-07 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0046_ans_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ans',
            name='answer',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
