# Generated by Django 4.1.3 on 2023-02-22 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0050_alter_result_correct_answer_alter_result_not_answer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='total_marks',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='subject',
            name='total_que',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
