# Generated by Django 4.1.3 on 2023-02-23 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0052_que_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='que',
            name='image',
            field=models.ImageField(default='', upload_to='que/images'),
        ),
    ]
