# Generated by Django 4.1.3 on 2023-02-24 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0053_alter_que_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='expiry_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
