# Generated by Django 4.1.3 on 2023-02-24 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0054_contact_expiry_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercourse',
            name='expiry_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
