# Generated by Django 4.1.3 on 2023-02-27 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0056_usercourse_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='ans',
            name='mark',
            field=models.IntegerField(default=0),
        ),
    ]
